title: Jp4Mobile
author: Jp
description: Jp4Mobile is mainly about iOS, Swift, and SwiftUI.
baseurl: ""
domain: www.Jp4Mobile.com
url: https://jp4mobile.com
logo: "/img/jp4mobile-logo-2x.png"
favicon: "/img/favicon.ico"
theme: minima
plugins:
  - jekyll-avatar
  - jekyll-feed
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
show_excerpts: true
excerpt_separator: "<!--more-->"
sass:
  style: compressed
include:
  - docs
exclude:
  - ../README.md
  - README.md
# SocialMedia
twitter_username: jplafond
github_username: Jp4Mobile
linkedin_username: jp-lafond
bluesky_username: jp.jp4mobile.com

# Mastodon instances
mastodon:
  - username: AltoidLover
    instance: tech.lgbt
  - username: Jp4Mobile
    instance: iosdev.space
  
# social_links:
#   - title: Jp4Mobile SampleCode
#     icon: github
#     url: "https://github.com/Jp4Mobile/SampleCode"
#   - title: Twitter
#     icon: x-twitter
#     url: "https://x.com/jplafond"
#   - title: Bluesky
#     icon: bluesky
#     url: "https://bsky.app/profile/jp.jp4mobile.com"
#   - title: Mastodon Tech.LGBT
#     icon: mastodon
#     url: "https://tech.lgbt/@AltoidLover"
#   - title: Mastodon iOSDev.space
#     icon: mastodon
#     url: "https://iosdev.space/@Jp4Mobile"

defaults:
  - scope:
      path: _posts
    values:
      author: Jp
      layout: post
